spring:
  data:
    mongodb:
      username: authserviceadmin
      password: password
      host: localhost
      port: 27019
      database: auth-service
      authentication-database: auth-service
server:
  port: 6094
application:
  security:
    jwt:
      secret-key: 2b9e785bfd84af3bf177a19177b2a1dd27e971a8d3e7394e66f68d9701a2d6f1
      expiration: 8640000 # 24 hours
logging:
  file:
    name: logs/auth-service/spring-boot.log
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
      springframework:
        data:
          jpa: INFO